---
title: "Dirichlet Multinomial Model"
author: "John Tipton"
date: "May 7, 2016"
output: html_document  
---
## To Do
- add in additive error terms
- Is there an identifiability issue in the Dirichlet-multinomial?


```{r setup, tidy=TRUE, echo=FALSE, message=FALSE, warning=FALSE, fig.height=3, fig.width=6, include=FALSE, eval=TRUE}
library(mvnfast)
library(ggplot2)
library(ggmcmc)
library(Matrix)
library(fields)
library(MCMCpack)
library(coda)
library(nimble)
library(snowfall)
library(mcmcplots)
library(data.table)
library(DirichletReg)
library(randomForest)
library(xtable)
library(gridExtra)
library(knitr)

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)

source("~/functions/multiplot.R")
n_adapt <- 150000
n_mcmc <- 150000
n_thin <- 150
n_chains <- 4
n_save <- n_mcmc / n_thin
n_samples <- n_chains * n_save
message <- 1000

N_pred <- 25
n_knots <- 30
corr_fun <- "gaussian"
  
if (!dir.exists("~/mvgp/figures/")) {
  dir.create("~/mvgp/figures/")
}
if (!dir.exists("~/mvgp/progress/")) {
  dir.create("~/mvgp/progress/")
}
if (!dir.exists("~/mvgp/progress/cross-validate/")) {
  dir.create("~/mvgp/progress/cross-validate/")
}
if (!dir.exists("~/mvgp/model-fit/")) {
  dir.create("~/mvgp/model-fit/")
}
if (!dir.exists("~/mvgp/model-fit/diagnostics/")) {
  dir.create("~/mvgp/model-fit/diagnostics")
}
```

# Load Testate Data and R code
```{r fullData, echo=FALSE, include=FALSE, eval=TRUE, results='hide'}
raw_data <- read.csv(file="~/testate/data/North American Raw Testate - Paleon 2017-Sheet1.csv", 
                     skip=6)

## subset to Booth 2008
raw_data <- raw_data[1:378, ]
y <- raw_data[, 12:85]
X <- raw_data$WTD..cm.

## Subset to Booth 2008 data
N <- 356
N_obs <- 356
y <- y[1:356, ]
X <- X[1:356]

## join species

source("~/testate/data/join-testate-booth.R")

## remove zeros
no_obs <- which(colSums(y) == 0)

## down to 47 species
y <- y[, -no_obs]

## Subset rare species
sum(y)
y <- y[, colSums(y) > 500]
# y <- y[, colSums(y) > 100]


N <- dim(y)[1]
d <- dim(y)[2]

## transform the data to percentages for use in transfer function models
y_prop <- y
for (i in 1:N) {
  y_prop[i, ] <- y_prop[i, ] / sum(y_prop[i, ])
}
```



```{r}
testatePlotData <- data.frame(species=as.factor(rep(colnames(y), each=N)),
                              Count=c(as.matrix(y_prop)), 
                              Wetness=rep(X, times=dim(y)[2]))


png(file="~/mvgp/figures/testate-plot.png", width=18, height=9,
    units="in", res=100)
# units="in", res=400)
ggplot(testatePlotData, aes(x=Wetness, y=Count, color=species, group=species)) +
  geom_point(alpha=0.25) +
  # geom_line(stat="smooth", method="loess", aes(y=Count, x=Wetness),
  #           alpha=0.5, lwd=1.25) +
  theme(legend.position="none") + ggtitle("Testate Composition vs. Water Table Depth") + 
  labs(x="Water Table Depth", y="Composition") + 
  theme(plot.title=element_text(size=40, face="bold", hjust=0.5)) + 
  theme(axis.text.x = element_text(size = 22), 
        axis.text.y = element_text(size = 22),
        axis.title.x = element_text(size = 22), 
        axis.title.y = element_text(size = 22))
dev.off()
```



```{r}
y <- as.matrix(y)
mean_X <- mean(X)
sd_X <- sd(X)
X <- (X - mean_X) / sd_X
X_knots <- seq(min(X, na.rm=TRUE)-1.25*sd(X, na.rm=TRUE), 
               max(X, na.rm=TRUE)+1.25*sd(X, na.rm=TRUE), length=n_knots)
```


## Held out for prediction

```{r fit-booth-2008, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
if (file.exists("~/mvgp/model-fit/fit-dm-mvgp-booth.RData")) {
  ## Load MCMC run
  load("~/mvgp/model-fit/fit-dm-mvgp-booth.RData")
} else {
  ##    
  ## Long running MCMC
  ##

  sample_idx <- sample(1:N, N_pred)
  
  ## Define parameters 
  params <- list(n_adapt=n_adapt, n_mcmc=n_mcmc, n_thin=n_thin,
                 X_knots=X_knots, message=message)
  
  parallelChains <- function (n_chains) {
    Rcpp::sourceCpp('~/mvgp/mcmc/mcmc-dirichlet-multinomial-mvgp.cpp')
    out <- coda::mcmc(mcmcRcpp(y[-sample_idx, ], X[-sample_idx], y[sample_idx, ], 
                               params, n_chain=n_chains, 
                               file_name="progress/dm-mvgp-booth.txt"))
  }
  
  ## Initalize multicore
  sfInit(parallel=TRUE, cpus=4)
  sfClusterSetupRNG()
  sfExport("y", "X", "params", "sample_idx", "N")
  sfLibrary(coda)
  
  ## create temporary progress file  
  file.create("./progress/dm-mvgp-booth.txt")
  
  ## run MCMC
  out <- sfLapply(1:4, parallelChains)
  
  sfStop()
    
  save(out, sample_idx, file="~/mvgp/model-fit/fit-dm-mvgp-booth.RData")
}
```


```{r, eval=TRUE}
## initialze posterior sample variables
mu_post <- matrix(0, n_samples, d)
eta_star_post <- array(0, dim=c(n_samples, n_knots, d))
zeta_post <-  array(0, dim=c(n_samples, N-N_pred, d))
alpha_post <-  array(0, dim=c(n_samples, N-N_pred, d))
zeta_pred_post <-  array(0, dim=c(n_samples, N_pred, d))
alpha_pred_post <-  array(0, dim=c(n_samples, N_pred, d))
phi_post <- rep(0,  n_samples)
tau2_post <- matrix(0,  n_samples, d)
X_post <- matrix(0,  n_samples, N_pred)
xi_post <- array(0,  dim=c(n_samples, choose(d, 2)))
R_post <- array(0, dim=c(n_samples, d, d))

for(i in 1:n_chains){
  mu_post[1:n_save + (i-1)*n_save, ] <- out[[i]]$mu
  eta_star_post[1:n_save + (i-1)*n_save, , ] <- out[[i]]$eta_star
  zeta_post[1:n_save + (i-1)*n_save, , ] <- out[[i]]$zeta
  alpha_post[1:n_save + (i-1)*n_save, , ] <- out[[i]]$alpha
  zeta_pred_post[1:n_save + (i-1)*n_save, , ] <- out[[i]]$zeta_pred
  alpha_pred_post[1:n_save + (i-1)*n_save, , ] <- out[[i]]$alpha_pred
  phi_post[1:n_save + (i-1)*n_save] <- out[[i]]$phi
  tau2_post[1:n_save + (i-1)*n_save, ] <- out[[i]]$tau2
  X_post[1:n_save + (i-1)*n_save, ] <- out[[i]]$X
  xi_post[1:n_save + (i-1)*n_save, ] <- out[[i]]$xi
  R_post[1:n_save + (i-1)*n_save, , ] <- out[[i]]$R
}          
```



```{r, eval=TRUE}
source("~/mvgp/functions/convert-to-coda.R")
out <- convert_to_coda(out)
```



```{r, eval=TRUE}
source("~/mvgp/nimble/functions/make_gelman_rubin.R")
Rhat <- make_gelman_rubin(out)
layout(matrix(1:9, 3, 3))
hist(Rhat[grepl("mu", names(Rhat))], main = "Rhat for mu")
hist(Rhat[grepl("eta_star", names(Rhat))], main = "Rhat for eta_star")
hist(Rhat[grepl("alpha", names(Rhat))], main = "Rhat for alpha")
hist(Rhat[grepl("zeta", names(Rhat))], main = "Rhat for zeta")
# hist(Rhat[grepl("epsilon", names(Rhat))], main = "Rhat for epsilon")
hist(Rhat[grepl("tau2", names(Rhat))], main = "Rhat for tau2")
hist(Rhat[grepl("X", names(Rhat))], main = "Rhat for X")
# plot(Rhat[grepl("phi", names(Rhat))], main = "Rhat for phi")
abline(h=1, col='red')
hist(Rhat[grepl("xi", names(Rhat))], main = "Rhat for xi")
hist(Rhat, main="All parameters")
Rhat[!is.finite(Rhat)] <- NA
Rhat[grepl("phi", names(Rhat))]
max(unlist(na.omit(Rhat)))
```



```{r, eval=TRUE}
## 
## Posterior plots
##

layout(matrix(1:9, 3, 3))
matplot(mu_post, type = 'l')
plot(phi_post, type='l')
matplot(tau2_post, type='l')
matplot(xi_post, type='l')
matplot(eta_star_post[, , 1], type='l')
matplot(eta_star_post[, , 2], type='l')
matplot(eta_star_post[, , 3], type='l')
matplot(eta_star_post[, , 4], type='l')
matplot(X_post, type='l')
```




```{r, eval=TRUE}
layout(matrix(1:4, 2, 2))
matplot(zeta_post[, 1, ], type='l')
matplot(zeta_post[, 2, ], type='l')
matplot(zeta_post[, 3, ], type='l')
matplot(zeta_post[, 4, ], type='l')
```



```{r, eval=TRUE}
layout(matrix(1:4, 2, 2))
matplot(zeta_pred_post[, 1, ], type='l')
matplot(zeta_pred_post[, 2, ], type='l')
matplot(zeta_pred_post[, 3, ], type='l')
matplot(zeta_pred_post[, 4, ], type='l')
```


```{r, eval=TRUE}
layout(matrix(1:4, 2, 2))
matplot(R_post[, , 1], type='l')
matplot(R_post[, , 2], type='l')
matplot(R_post[, , 3], type='l')
matplot(R_post[, , 4], type='l')
```




```{r, eval=TRUE}
layout(matrix(1:4, 2, 2))
matplot(alpha_post[, 1, ], type='l')
matplot(alpha_post[, 2, ], type='l')
matplot(alpha_post[, 3, ], type='l')
matplot(alpha_post[, 4, ], type='l')
```



```{r, eval=TRUE}
idx <- order(X[-sample_idx])
zeta_post_mean <- apply(zeta_post, c(2,3), mean)
matplot(X[-sample_idx][idx], zeta_post_mean[idx, ], type='l')
```



```{r, eval=TRUE}
layout(matrix(1, 1, 1))
matplot(apply(X_post, 2, mean), type='l',
        ylim=c(-5, 5))
matplot(apply(X_post, 2, quantile, prob = 0.025), 
        type='l', add=TRUE, lty=2)
matplot(apply(X_post, 2, quantile, prob = 0.975), 
        type='l', add=TRUE, lty=2)
lines(X[sample_idx], col = 'red')
```



```{r, eval=TRUE}
layout(matrix(1, 1, 1))
idx <- order(X[sample_idx])
matplot(apply(X_post, 2, mean)[idx], type='l',
        ylim=c(-5, 5))
matplot(apply(X_post, 2, quantile, prob = 0.025)[idx], 
        type='l', add=TRUE, lty=2)
matplot(apply(X_post, 2, quantile, prob = 0.975)[idx], 
        type='l', add=TRUE, lty=2)
lines(X[sample_idx][idx], col = 'red')
```



```{r, include=FALSE}
## sorted to increase
idx <- order(X[sample_idx])
X_ci <- apply(X_post[, idx]*sd_X + mean_X, 2, sort)[(0.025*n_samples+1):(0.975*n_samples), ]
sim.df <- data.frame(Covariate=c(X_ci),
                     Observation=factor(rep((1:length(sample_idx)),
                                            each=n_samples*0.95)),
                     truth=rep(X[sample_idx][idx]*sd_X + mean_X,
                               each=n_samples*0.95))

##  only add observation ticks every 10 observations
png(file="~/mvgp/figures/testate-predictions.png", width=6, height=3,
    units="in", res=100)
    # units="in", res=400)
ggplot(sim.df, aes(Observation, Covariate)) +
  geom_violin(position="identity") +
  geom_point(aes(Observation, truth), color="red") +
  scale_x_discrete(breaks=seq(5, 50, 5)) + 
  labs(x="Observation", y="Unobserved Water Table Depth")
dev.off()
```




```{r, eval=TRUE}
Omega_post_mean <- matrix(0, d, d)
for (i in 1:n_samples) {
  Omega_post_mean <- Omega_post_mean + 
    1/n_samples * t(R_post[i, , ]) %*% R_post[i, , ]
}
# layout(matrix(1:4, 2, 2))
# hist(Omega_post_mean)
# hist(cov2cor(Sigma))
# hist(Omega_post_mean - cov2cor(Sigma))
library(GGally)
colnames(Omega_post_mean) <- colnames(y)
png(file="~/mvgp/figures/testate-correlations.png", width=18, height=9,
    units="in", res=100)
# units="in", res=400)
ggcorr(data=NULL, cor_matrix=Omega_post_mean, hjust=0.9, layout.exp=3, size=10) + 
    ggtitle("Posterior Correlations") +   
  theme(plot.title=element_text(size=40, face="bold", hjust=0.5))

dev.off()
```



```{r}
alpha_post_mean <- apply(alpha_post, c(2, 3), mean)
alpha_post_sum_to_one <- alpha_post
for (k in 1:n_samples) {
  for (i in 1:(N-length(sample_idx))) {
    alpha_post_sum_to_one[k, i, ] <- alpha_post_sum_to_one[k, i, ] /
        sum(alpha_post_sum_to_one[k, i, ])
  }
}
alpha_post_lower_95 <- apply(alpha_post_sum_to_one, c(2, 3), quantile, prob=0.025)
alpha_post_upper_95 <- apply(alpha_post_sum_to_one, c(2, 3), quantile, prob=0.975)

zeta_post_mean <- apply(zeta_post, c(2, 3), mean)
mu_post_mean <- apply(mu_post, 2, mean)
p_alpha <- matrix(0, N-N_pred, d)
for (i in 1:(N-N_pred)) {
  p_alpha[i, ] <- exp(mu_post_mean + zeta_post_mean[i, ]) / sum(exp(mu_post_mean + zeta_post_mean[i, ]))
  # p_alpha[i, ] <- alpha_post_mean[i, ] / sum(alpha_post_mean[i, ])
}
y_prop <- y
for (i in 1:N) {
  y_prop[i, ] <- y[i, ] / sum(y[i, ])
}

fitPlotData <- data.frame(species=as.factor(rep(colnames(y), each=N-N_pred)), 
                          count=c(y_prop[-sample_idx, ]), 
                          depth=rep(X[-sample_idx]*sd_X + mean_X, times=d),
                          alpha=c(p_alpha), 
                          alpha_lower=c(alpha_post_lower_95), 
                          alpha_upper=c(alpha_post_upper_95))

g1_post <- ggplot(fitPlotData, aes(x=depth, y=count, color=species, group=species)) + 
  geom_point(alpha=0.25) + theme(legend.position="none") +
  geom_ribbon(aes(ymin=alpha_lower, ymax=alpha_upper, fill=species, group=species),
              linetype=0, alpha=0.5) + 
  ggtitle("Composition vs. Water Table Depth") + 
  geom_line(aes(x=depth, y=alpha, col = species), fitPlotData, lwd=1.25) +
  labs(x="Water Table Depth", y="Composition") 

g2_post <- ggplot(fitPlotData, aes(x=depth, y=count, color=species, group=species)) + 
  geom_point(alpha=0.25) + theme(legend.position="none") +
  geom_ribbon(aes(ymin=alpha_lower, ymax=alpha_upper, fill=species, group=species),
                linetype=0, alpha=0.5) + 
  ggtitle("Composition vs. Water Table Depth") + 
  theme(plot.title=element_text(size=40, face="bold", hjust=0.5)) + 
  geom_line(aes(x=depth, y=alpha, col = species), fitPlotData, lwd=1.25) + 
  facet_wrap( ~ species, ncol = 4) + 
  labs(x="Water Table Depth", y="Composition")  + 
  theme(strip.text.x = element_text(size = 22), 
        axis.text.x = element_text(size = 22), 
        axis.text.y = element_text(size = 22),
        axis.title.x = element_text(size = 22), 
        axis.title.y = element_text(size = 22))

source("~/functions/multiplot.R")
png(file="~/mvgp/figures/testate-fit.png", width=6, height=3,
    units="in", res=100)
    # units="in", res=400)
multiplot(g1_post, g2_post, cols=2)
dev.off()

library(grid)
library(gtable)
g <- ggplotGrob(g2_post)
pos =  c(subset(g$layout, grepl("panel", g$layout$name), select = t))
for(i in pos) g$heights[i-1] = unit(0.8,"cm")

# The grobs that need their heights changed:
grobs = which(grepl("strip", g$layout$name))
for(i in grobs) g$grobs[[i]]$heights <-  unit(1, "npc")      
grid.newpage()
grid.draw(g)

png(file="~/mvgp/figures/testate-fit2.png", width=18, height=9,
    units="in", res=100)
# units="in", res=100)
# units="in", res=400)
grid.draw(g)
g
dev.off()
```



## Cross-validation - Booth 2008

```{r cv-mvgp-booth}
y_cv <- y
y_cv_prop <- y_cv

## transform the data to percentages for use in transfer function models
for (i in 1:N) {
  y_cv_prop[i, ] <- y_cv_prop[i, ] / sum(y_cv_prop[i, ])
}
colnames(y_cv) <- as.character(1:dim(y_cv)[2])
colnames(y_cv_prop) <- as.character(1:dim(y_cv)[2])
X_cv <- X
set.seed(11)
# idx <- 
kfold <- 12
folds <- cut(sample(1:N, N), breaks=kfold, labels=FALSE)

  params <- list(n_adapt=n_adapt, n_mcmc=n_mcmc, n_thin=n_thin,
                 X_knots=X_knots, message=message)


## load cross validation function
source("~/mvgp/functions/makeCV-dm-mvgp.R")

## Setup computing cluster
library(snowfall)
library(parallel)
library(rlecuyer)
## define models to fit
# models <- c("MVGP")
models <- c("MVGP", "GAM", "WA", "MAT", "MLRC", "WAPLS", "RF")#, "GJAM")
# models <- c("MVGP", "WA", "MLRC", "WAPLS", "RF", "GJAM")
# models <- c("MVGP", "basis", "WA", "MLRC", "WAPLS", "RF", "GJAM")
## determines the number of cores on the machine
cps <- 4
# cps <- 5
## Initalize multicore 
sfInit(parallel=TRUE, cpus=cps)
## Setup random number generator on the cluster
sfClusterSetupRNG()
# export global variables
sfExport("y_cv", "y_cv_prop", "X_cv", "folds", "makeCV", "params",
         "mean_X", "sd_X", "kfold", "d", "n_chains")

## Fit cross-validation
for (model_name in models) {
  if (!file.exists(paste0("~/mvgp/model-fit/dm-mvgp-cv-booth-", 
                          model_name, ".RData"))) {
    ##
    ## Long running CV
    ##
    if (model_name == "MVGP") {
      ## create temporary progress file  
      file.create("~/mvgp/progress/cross-validate/dm-mvgp-cv.txt")
    }
    CV_out <- sfSapply(1:kfold, makeCV, model_name=model_name, y_cv=y_cv,
                       y_cv_prop=y_cv_prop, X_cv=X_cv, params=params, 
                       folds=folds)
    CRPS <- unlist(CV_out[1, ])
    MSPE <- unlist(CV_out[2, ])
    MAE <- unlist(CV_out[3, ])
    coverage <- unlist(CV_out[4, ])
    save(CRPS, MSPE, MAE, coverage, 
         file=paste0("~/mvgp/model-fit/dm-mvgp-cv-booth-", 
                     model_name, ".RData"))
  }
}
  ## ends snowfall session
sfStop()

```







```{r process-mvgp-CV-booth, echo=FALSE, eval=TRUE, message=FALSE, include=FALSE, warning=FALSE, cache=TRUE}
# models <- c("MVGP", "WA", "MLRC", "WAPLS", "RF", "GJAM")
CRPS_out <- matrix(0, length(models), N)
MSPE_out <- matrix(0, length(models), N)
MAE_out <- matrix(0, length(models), N)
coverage_out <- matrix(0, length(models), N)
idx_model <- 1
for (model_fit in models) {
  ## Load MCMC run
  load(paste0("~/mvgp/model-fit/dm-mvgp-cv-booth-", model_fit, ".RData"))
  CRPS_out[idx_model, ] <- CRPS
  MSPE_out[idx_model, ] <- MSPE
  MAE_out[idx_model, ] <- MAE
  coverage_out[idx_model, ] <- coverage
  idx_model <- idx_model + 1
}       

CRPS <- data.frame(t(apply(CRPS_out[-c(6, 7), ], 1, mean, na.rm=TRUE)))
MSPE <- data.frame(t(apply(MSPE_out[-c(6, 7), ], 1, mean)))
MAE <- data.frame(t(apply(MAE_out[-c(6, 7), ], 1, mean)))
coverage <- data.frame(100/N*t(apply(coverage_out[-c(6, 7), ], 1, sum)))

# colnames(CRPS) <- c("MVGP", "GAM", "WA", "MAT", "MLRC", "RF", "GJAM")
# colnames(MAE) <- c("MVGP", "GAM", "WA", "MAT", "MLRC", "RF", "GJAM")
# colnames(MSPE) <- c("MVGP", "GAM", "WA", "MAT", "MLRC", "RF", "GJAM")
# colnames(coverage) <- c("MVGP", "GAM", "WA", "MAT", "MLRC", "RF", "GJAM")
# colnames(CRPS) <- c("MVGP", "GAM", "WA", "MAT", "MLRC", "GJAM")
# colnames(MAE) <- c("MVGP", "GAM", "WA", "MAT", "MLRC", "GJAM")
# colnames(MSPE) <- c("MVGP", "GAM", "WA", "MAT", "MLRC", "GJAM")
# colnames(coverage) <- c("MVGP", "GAM", "WA", "MAT", "MLRC", "GJAM")
colnames(CRPS) <- c("MVGP", "GAM", "WA", "MAT", "MLRC")
colnames(MAE) <- c("MVGP", "GAM", "WA", "MAT", "MLRC")
colnames(MSPE) <- c("MVGP", "GAM", "WA", "MAT", "MLRC")
colnames(coverage) <- c("MVGP", "GAM", "WA", "MAT", "MLRC")
```



```{r}
library(xtable)
sim_results <- rbind(CRPS, MSPE, MAE, coverage)
rownames(sim_results) <- c("CRPS", "MSPE", "MAE", "95% CI coverage")
print(xtable(sim_results, digits=4), file="results/cvResults-dm-mvgp-booth.tex", 
      floating=FALSE)
```



```{r}
kable(sim_results)
```



```{r}
## Change to ggplot2
library(reshape2)
library(ggplot2)
rownames(CRPS_out) <- models
CRPS_gg <- melt(CRPS_out[-c(6, 7), ])
names(CRPS_gg) <- c("Model", "Observation", "value")
CRPS_gg$Model <- factor(CRPS_gg$Model)
gg1 <- ggplot(CRPS_gg, aes(x=Model, y=value, color=Model, group=Model), 
              palette="PuOr") +
  geom_violin(alpha=0.5) + scale_y_continuous(name=NULL) + ggtitle("CRPS") +
  stat_summary(fun.y=mean, geom="point")

rownames(MAE_out) <- models
MAE_gg <- melt(MAE_out[-c(6, 7), ])
names(MAE_gg) <- c("Model", "Observation", "value")
MAE_gg$Model <- factor(MAE_gg$Model)
gg2 <- ggplot(MAE_gg, aes(x=Model, y=value, color=Model, group=Model), 
              palette="PuOr") +
  geom_violin(alpha=0.5) +  scale_y_continuous(name=NULL) + ggtitle("MAE") +
  stat_summary(fun.y=mean, geom="point")

rownames(MSPE_out) <- models
MSPE_gg <- melt(MSPE_out[-c(6, 7), ])
names(MSPE_gg) <- c("Model", "Observation", "value")
MSPE_gg$Model <- factor(MSPE_gg$Model)
gg3 <- ggplot(MSPE_gg, aes(x=Model, y=value, color=Model, group=Model), 
       palette="PuOr") +
  geom_violin(alpha=0.5) +  scale_y_continuous(name=NULL) + ggtitle("MSPE") +
  stat_summary(fun.y=mean, geom="point")
```



```{r}
# png(file=paste("~/testate",
#                "/figures/",
#                "processCV-1-mvgp.png",
#                "", sep=""), width=6, height=4.5, units="in", res=400)
multiplot(gg1 + theme(legend.position="none"),
          gg2 + theme(legend.position="none"),
          gg3 + theme(legend.position="none"), cols=3)
# dev.off()
```



```{r}
matplot(t(CRPS_out), type='l', main="CRPS", col=adjustcolor(1:6, alpha.f=0.25))
matplot(t(MSPE_out), type='l', main="MSPE", col=adjustcolor(1:6, alpha.f=0.25))
matplot(t(MAE_out), type='l', main="MAE", col=adjustcolor(1:6, alpha.f=0.25))
# matplot(t(coverage_out), type='l', main="Coverage")
```


# Load Testate Data and R code - Full Data
```{r readData, echo=FALSE, include=FALSE, eval=TRUE, results='hide'}
raw_data <- read.csv(file="~/testate/data/North American Raw Testate - Paleon 2017-Sheet1.csv", 
                     skip=6)

y <- raw_data[, 12:85]
X <- raw_data$WTD..cm.

## join species

source("~/testate/data/join-testate.R")

## remove censored observations
censored <- which(X == 50)
X <- X[- censored]
y <- y[-censored, ]

## remove zeros
no_obs <- which(colSums(y) == 0)

## down to 47 species
y <- y[, -no_obs]

## Subset rare species
sum(y)
y <- y[, colSums(y) > 500]
# y <- y[, colSums(y) > 100]

mean_X <- mean(X)
sd_X <- sd(X)
X <- (X - mean_X) / sd_X
N <- nrow(y)

N <- dim(y)[1]
d <- dim(y)[2]

## transform the data to percentages for use in transfer function models
y_prop <- y
for (i in 1:N) {
  y_prop[i, ] <- y_prop[i, ] / sum(y_prop[i, ])
}
```



```{r}
testatePlotData <- data.frame(species=as.factor(rep(names(y), each=N)),
                              Count=c(as.matrix(y_prop)), 
                              Wetness=rep(X, times=dim(y)[2]))


ggplot(testatePlotData, aes(x=Wetness, y=Count, color=species, group=species)) +
  geom_point(alpha=0.05) +
  geom_line(stat="smooth", method="loess", aes(y=Count, x=Wetness),
            alpha=0.5, lwd=1.25) +
  theme(legend.position="none") + ggtitle("Species composition vs. wetness")
```


```{r}
y <- as.matrix(y)
mean_X <- mean(X)
sd_X <- sd(X)
X <- (X - mean_X) / sd_X
X_knots <- seq(min(X, na.rm=TRUE)-1.25*sd(X, na.rm=TRUE), 
               max(X, na.rm=TRUE)+1.25*sd(X, na.rm=TRUE), length=n_knots)
```

## Cross-validation - Full Data

```{r cv-dm-mvgp}
y_cv <- y
y_cv_prop <- y_cv

## transform the data to percentages for use in transfer function models
for (i in 1:N) {
  y_cv_prop[i, ] <- y_cv_prop[i, ] / sum(y_cv_prop[i, ])
}
colnames(y_cv) <- as.character(1:dim(y_cv)[2])
colnames(y_cv_prop) <- as.character(1:dim(y_cv)[2])
X_cv <- X
set.seed(11)
# idx <- 
kfold <- 12
folds <- cut(sample(1:N, N), breaks=kfold, labels=FALSE)

params <- list(n_adapt=n_adapt, n_mcmc=n_mcmc, n_thin=n_thin,
               X_knots=X_knots, message=message)

## load cross validation function
source("~/mvgp/functions/makeCV-dm-mvgp.R")

## Setup computing cluster
library(snowfall)
library(parallel)
library(rlecuyer)
## define models to fit
# models <- c("MVGP")
models <- c("MVGP", "WA", "MLRC", "WAPLS", "RF", "GJAM")
# models <- c("MVGP", "basis", "WA", "MLRC", "WAPLS", "RF", "GJAM")
## determines the number of cores on the machine
cps <- 4
# cps <- 5
## Initalize multicore 
sfInit(parallel=TRUE, cpus=cps)
## Setup random number generator on the cluster
sfClusterSetupRNG()
# export global variables
sfExport("y_cv", "y_cv_prop", "X_cv", "folds", "makeCV", "params",
         "mean_X", "sd_X", "kfold", "d", "n_chains")

## Fit cross-validation
for (model_name in models) {
  if (!file.exists(paste("~/mvgp/model-fit/dm-mvgp-cv-full-", model_name,
                         ".RData", sep=""))) {
    ##
    ## Long running CV
    ##
    if (model_name == "MVGP") {
      ## create temporary progress file  
      file.create("~/mvgp/progress/cross-validate/dm-mvgp-cv-full.txt")
    }
    CV_out <- sfSapply(1:kfold, makeCV, model_name=model_name, y_cv=y_cv,
                       y_cv_prop=y_cv_prop, X_cv=X_cv, params=params, 
                       folds=folds)
    CRPS <- unlist(CV_out[1, ])
    MSPE <- unlist(CV_out[2, ])
    MAE <- unlist(CV_out[3, ])
    coverage <- unlist(CV_out[4, ])
    save(CRPS, MSPE, MAE, coverage, 
         file=paste0("~/mvgp/model-fit/dm-mvgp-cv-full-", model_name, ".RData"))
  }
}
  ## ends snowfall session
sfStop()

```







```{r processCV, echo=FALSE, eval=TRUE, message=FALSE, include=FALSE, warning=FALSE, cache=TRUE}
# models <- c("quantile", "basis", "WA", "MLRC", "WAPLS", "RF"), "GJAM"
models <- c("MVGP", "WA", "MLRC", "WAPLS", "RF", "GJAM")
CRPS_out <- matrix(0, length(models), N)
MSPE_out <- matrix(0, length(models), N)
MAE_out <- matrix(0, length(models), N)
coverage_out <- matrix(0, length(models), N)
idx_model <- 1
for (model_fit in models) {
  ## Load MCMC run
  load(paste0("~/mvgp/model-fit/dm-mvgp-cv-full-", model_fit, ".RData"))
  CRPS_out[idx_model, ] <- CRPS
  MSPE_out[idx_model, ] <- MSPE
  MAE_out[idx_model, ] <- MAE
  coverage_out[idx_model, ] <- coverage
  idx_model <- idx_model + 1
}       

CRPS <- data.frame(t(apply(CRPS_out[-4, ], 1, mean)))
MSPE <- data.frame(t(apply(MSPE_out[-4, ], 1, mean)))
MAE <- data.frame(t(apply(MAE_out[-4, ], 1, mean)))
coverage <- data.frame(100/N*t(apply(coverage_out[-4, ], 1, sum)))

colnames(CRPS) <- c("MVGP", "WA", "MLRC", "RF", "GJAM")
colnames(MAE) <- c("MVGP", "WA", "MLRC", "RF", "GJAM")
colnames(MSPE) <- c("MVGP", "WA", "MLRC", "RF", "GJAM")
colnames(coverage) <- c("MVGP", "WA", "MLRC", "RF", "GJAM")
```



```{r}
library(xtable)
sim_results <- rbind(CRPS, MSPE, MAE, coverage)
rownames(sim_results) <- c("CRPS", "MSPE", "MAE", "95% CI coverage")
print(xtable(sim_results, digits=4), file="results/cvResults-dm-mvgp-full.tex", 
      floating=FALSE)
```



```{r}
kable(sim_results)
```


```{r}
## Change to ggplot2
library(reshape2)
library(ggplot2)
rownames(CRPS_out) <- c("MVGP", "WA", "MLRC", "WAPLS", "RF")
CRPS_gg <- melt(CRPS_out[-4, ])
names(CRPS_gg) <- c("Model", "Observation", "value")
CRPS_gg$Model <- factor(CRPS_gg$Model)
gg1 <- ggplot(CRPS_gg, aes(x=Model, y=value, color=Model, group=Model), 
              palette="PuOr") +
  geom_violin(alpha=0.5) + scale_y_continuous(name=NULL) + ggtitle("CRPS") +
  stat_summary(fun.y=mean, geom="point")

rownames(MAE_out) <- c("MVGP", "WA", "MLRC", "WAPLS", "RF")
MAE_gg <- melt(MAE_out[-4, ])
names(MAE_gg) <- c("Model", "Observation", "value")
MAE_gg$Model <- factor(MAE_gg$Model)
gg2 <- ggplot(MAE_gg, aes(x=Model, y=value, color=Model, group=Model), 
              palette="PuOr") +
  geom_violin(alpha=0.5) +  scale_y_continuous(name=NULL) + ggtitle("MAE") +
  stat_summary(fun.y=mean, geom="point")

rownames(MSPE_out) <- c("MVGP", "WA", "MLRC", "WAPLS", "RF")
MSPE_gg <- melt(MSPE_out[-4, ])
names(MSPE_gg) <- c("Model", "Observation", "value")
MSPE_gg$Model <- factor(MSPE_gg$Model)
gg3 <- ggplot(MSPE_gg, aes(x=Model, y=value, color=Model, group=Model), 
       palette="PuOr") +
  geom_violin(alpha=0.5) +  scale_y_continuous(name=NULL) + ggtitle("MSPE") +
  stat_summary(fun.y=mean, geom="point")
```

```{r}
multiplot(gg1 + theme(legend.position="none"),
          gg2 + theme(legend.position="none"),
          gg3 + theme(legend.position="none"), cols=3)
```


```{r, eval=FALSE}
# png(file=paste("~/testate",
#                "/figures/",
#                "processCV-1-mvgp.png",
#                "", sep=""), width=6, height=4.5, units="in", res=400)
multiplot(gg1 + theme(legend.position="none"),
          gg2 + theme(legend.position="none"),
          gg3 + theme(legend.position="none"), cols=3)
# dev.off()
```


```{r}
matplot(t(CRPS_out), type='l', main="CRPS", col=adjustcolor(1:6, alpha.f=0.25))
matplot(t(MSPE_out), type='l', main="MSPE", col=adjustcolor(1:6, alpha.f=0.25))
matplot(t(MAE_out), type='l', main="MAE", col=adjustcolor(1:6, alpha.f=0.25))
# matplot(t(coverage_out), type='l', main="Coverage")
```


# Load Testate Data and R code for reduced species
```{r reducedData, echo=FALSE, include=FALSE, eval=TRUE, results='hide'}
raw_data <- read.csv(file="~/testate/data/North American Raw Testate - Paleon 2017-Sheet1.csv", 
                     skip=6)

y <- raw_data[, 12:85]
X <- raw_data$WTD..cm.

## join species

source("~/testate/data/join-testate.R")

## remove censored observations
censored <- which(X == 50)
X <- X[- censored]
y <- y[-censored, ]

## remove zeros
no_obs <- which(colSums(y) == 0)

## down to 47 species
y <- y[, -no_obs]

## Subset rare species
sum(y)
y <- y[, colSums(y) > 1000]
# y <- y[, colSums(y) > 100]

mean_X <- mean(X)
sd_X <- sd(X)
X <- (X - mean_X) / sd_X
N <- nrow(y)

N <- dim(y)[1]
d <- dim(y)[2]

## transform the data to percentages for use in transfer function models
y_prop <- y
for (i in 1:N) {
  y_prop[i, ] <- y_prop[i, ] / sum(y_prop[i, ])
}
```



```{r}
testatePlotData <- data.frame(species=as.factor(rep(names(y), each=N)),
                              Count=c(as.matrix(y_prop)), 
                              Wetness=rep(X, times=dim(y)[2]))


ggplot(testatePlotData, aes(x=Wetness, y=Count, color=species, group=species)) +
  geom_point(alpha=0.05) +
  geom_line(stat="smooth", method="loess", aes(y=Count, x=Wetness),
            alpha=0.5, lwd=1.25) +
  theme(legend.position="none") + ggtitle("Species composition vs. wetness")
```


```{r}
y <- as.matrix(y)
mean_X <- mean(X)
sd_X <- sd(X)
X <- (X - mean_X) / sd_X
X_knots <- seq(min(X, na.rm=TRUE)-1.25*sd(X, na.rm=TRUE), 
               max(X, na.rm=TRUE)+1.25*sd(X, na.rm=TRUE), length=n_knots)
```

## Cross-validation on reduced data

```{r cv-dm-mvgp-reduced}
y_cv <- y
y_cv_prop <- y_cv

## transform the data to percentages for use in transfer function models
for (i in 1:N) {
  y_cv_prop[i, ] <- y_cv_prop[i, ] / sum(y_cv_prop[i, ])
}
colnames(y_cv) <- as.character(1:dim(y_cv)[2])
colnames(y_cv_prop) <- as.character(1:dim(y_cv)[2])
X_cv <- X
set.seed(11)
# idx <- 
kfold <- 12
folds <- cut(sample(1:N, N), breaks=kfold, labels=FALSE)

params <- list(n_adapt=n_adapt, n_mcmc=n_mcmc, n_thin=n_thin,
               X_knots=X_knots, message=message)

## load cross validation function
source("~/mvgp/functions/makeCV-dm-mvgp.R")

## Setup computing cluster
library(snowfall)
library(parallel)
library(rlecuyer)
## define models to fit
# models <- c("MVGP")
models <- c("MVGP", "WA", "MLRC", "WAPLS", "RF")
# models <- c("MVGP", "basis", "WA", "MLRC", "WAPLS", "RF")
## determines the number of cores on the machine
cps <- 4
# cps <- 5
## Initalize multicore 
sfInit(parallel=TRUE, cpus=cps)
## Setup random number generator on the cluster
sfClusterSetupRNG()
# export global variables
sfExport("y_cv", "y_cv_prop", "X_cv", "folds", "makeCV", "params",
         "mean_X", "sd_X", "kfold", "d", "n_chains")

## Fit cross-validation
for (model_name in models) {
  if (!file.exists(paste("~/mvgp/model-fit/dm-mvgp-cv-full-reduced-", model_name,
                         ".RData", sep=""))) {
    ##
    ## Long running CV
    ##
    if (model_name == "MVGP") {
      ## create temporary progress file  
      file.create("~/mvgp/progress/cross-validate/dm-mvgp-cv-full.txt")
    }
    CV_out <- sfSapply(1:kfold, makeCV, model_name=model_name, y_cv=y_cv,
                       y_cv_prop=y_cv_prop, X_cv=X_cv, params=params, 
                       folds=folds)
    CRPS <- unlist(CV_out[1, ])
    MSPE <- unlist(CV_out[2, ])
    MAE <- unlist(CV_out[3, ])
    coverage <- unlist(CV_out[4, ])
    save(CRPS, MSPE, MAE, coverage, 
         file=paste0("~/mvgp/model-fit/dm-mvgp-cv-full-reduced-", model_name, ".RData"))
  }
}
  ## ends snowfall session
sfStop()

```







```{r processCVreduced, echo=FALSE, eval=TRUE, message=FALSE, include=FALSE, warning=FALSE, cache=TRUE}
# models <- c("quantile", "basis", "WA", "MLRC", "WAPLS", "RF")
models <- c("MVGP", "WA", "MLRC", "WAPLS", "RF")
CRPS_out <- matrix(0, length(models), N)
MSPE_out <- matrix(0, length(models), N)
MAE_out <- matrix(0, length(models), N)
coverage_out <- matrix(0, length(models), N)
idx_model <- 1
for (model_fit in models) {
  ## Load MCMC run
  load(paste0("~/mvgp/model-fit/dm-mvgp-cv-full-reduced-", model_fit, ".RData"))
  CRPS_out[idx_model, ] <- CRPS
  MSPE_out[idx_model, ] <- MSPE
  MAE_out[idx_model, ] <- MAE
  coverage_out[idx_model, ] <- coverage
  idx_model <- idx_model + 1
}       

CRPS <- data.frame(t(apply(CRPS_out[-4, ], 1, mean)))
MSPE <- data.frame(t(apply(MSPE_out[-4, ], 1, mean)))
MAE <- data.frame(t(apply(MAE_out[-4, ], 1, mean)))
coverage <- data.frame(100/N*t(apply(coverage_out[-4, ], 1, sum)))

colnames(CRPS) <- c("MVGP", "WA", "MLRC", "RF")
colnames(MAE) <- c("MVGP", "WA", "MLRC", "RF")
colnames(MSPE) <- c("MVGP", "WA", "MLRC", "RF")
colnames(coverage) <- c("MVGP", "WA", "MLRC", "RF")
```



```{r}
library(xtable)
sim_results <- rbind(CRPS, MSPE, MAE, coverage)
rownames(sim_results) <- c("CRPS", "MSPE", "MAE", "95% CI coverage rates")
print(xtable(sim_results, digits=4), file="results/cvResults-dm-mvgp-full-reduced.tex", 
      floating=FALSE)
```



```{r}
kable(sim_results)
```



```{r}
## Change to ggplot2
library(reshape2)
library(ggplot2)
rownames(CRPS_out) <- c("MVGP", "WA", "MLRC", "WAPLS", "RF")
CRPS_gg <- melt(CRPS_out[-4, ])
names(CRPS_gg) <- c("Model", "Observation", "value")
CRPS_gg$Model <- factor(CRPS_gg$Model)
gg1 <- ggplot(CRPS_gg, aes(x=Model, y=value, color=Model, group=Model), 
              palette="PuOr") +
  geom_violin(alpha=0.5) + scale_y_continuous(name=NULL) + ggtitle("CRPS") +
  stat_summary(fun.y=mean, geom="point")

rownames(MAE_out) <- c("MVGP", "WA", "MLRC", "WAPLS", "RF")
MAE_gg <- melt(MAE_out[-4, ])
names(MAE_gg) <- c("Model", "Observation", "value")
MAE_gg$Model <- factor(MAE_gg$Model)
gg2 <- ggplot(MAE_gg, aes(x=Model, y=value, color=Model, group=Model), 
              palette="PuOr") +
  geom_violin(alpha=0.5) +  scale_y_continuous(name=NULL) + ggtitle("MAE") +
  stat_summary(fun.y=mean, geom="point")

rownames(MSPE_out) <- c("MVGP", "WA", "MLRC", "WAPLS", "RF")
MSPE_gg <- melt(MSPE_out[-4, ])
names(MSPE_gg) <- c("Model", "Observation", "value")
MSPE_gg$Model <- factor(MSPE_gg$Model)
gg3 <- ggplot(MSPE_gg, aes(x=Model, y=value, color=Model, group=Model), 
       palette="PuOr") +
  geom_violin(alpha=0.5) +  scale_y_continuous(name=NULL) + ggtitle("MSPE") +
  stat_summary(fun.y=mean, geom="point")
```



```{r}
# png(file=paste("~/testate",
#                "/figures/",
#                "processCV-1-mvgp.png",
#                "", sep=""), width=6, height=4.5, units="in", res=400)
multiplot(gg1 + theme(legend.position="none"),
          gg2 + theme(legend.position="none"),
          gg3 + theme(legend.position="none"), cols=3)
# dev.off()
```



```{r}
matplot(t(CRPS_out), type='l', main="CRPS", col=adjustcolor(1:6, alpha.f=0.25))
matplot(t(MSPE_out), type='l', main="MSPE", col=adjustcolor(1:6, alpha.f=0.25))
matplot(t(MAE_out), type='l', main="MAE", col=adjustcolor(1:6, alpha.f=0.25))
# matplot(t(coverage_out), type='l', main="Coverage")
```
